// Generated by CoffeeScript 2.0.2

import React, { Component } from 'react'
import DatePicker from 'react-datepicker'
;
var Dates;

Dates = class Dates extends Component {
  render() {
    return <DatePicker selected={this.state.startDate} onChange={this.handleChange} showTimeSelect showTimeSelectOnly timeIntervals={15} dateFormat="LT" timeCaption="Time" />;
  }

};

export default Dates;
