// Generated by CoffeeScript 2.0.2

import React, { Component } from 'react'
import Dates from './components/Dates'
import Video from './components/Video'
import './App.css'
;
var App;

App = class App extends Component {
  render() {
    return <div className="App">
        <div className="App-header">
        	<h2>Tim App</h2>
        	<div className="App-top-text">
        		<h1>This is my app</h1>
           </div>
       	   </div>
      </div>;
  }

};

export default App;
