// Generated by CoffeeScript 2.0.2

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
;
it('renders without crashing', () => {
  var div;
  div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
